showmoney: add TextUtil isEmpty() to check string in SearchAdapter
使用了Textutil.isEmpty()方法来判断字符串是否是空字符串。
如果不判断会抛出异常的：
java.lang.NullPointerException: cs == null
at java.lang.String.contains(String.java:1926)
at com.cardinfolink.yunshouyin.view.SearchAdapter$SearchFilter.performFiltering(SearchAdapter.java:98)
at android.widget.Filter$RequestHandler.handleMessage(Filter.java:234)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:136)
at android.os.HandlerThread.run(HandlerThread.java:61)

Change-Id: Id06a4ab1f19af908dc526bf034f45c71d2244fac
Signed-off-by: Minghui Ma <mamh.ma@cardinfolink.com>
(cherry picked from commit 68b5e34997b8229ccac8675a7d60f5d69d3c8bdc)