showmoeny: add check string isEmpty  in EncoderUtil
加入了 是否是null的判断，不然 修改密码之后，拉取账单 会报错的

 java.lang.RuntimeException: An error occured while executing doInBackground()
 >--at android.os.AsyncTask$3.done(AsyncTask.java:299)
 >--at java.util.concurrent.FutureTask$Sync.innerSetException(FutureTask.java:273)
 >--at java.util.concurrent.FutureTask.setException(FutureTask.java:124)
 >--at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:307)
 >--at java.util.concurrent.FutureTask.run(FutureTask.java:137)
 >--at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230)
 >--at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
 >--at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
 >--at java.lang.Thread.run(Thread.java:856)
 Caused by: java.lang.NullPointerException
 >--at com.cardinfolink.yunshouyin.util.EncoderUtil.Encrypt(EncoderUtil.java:13)
 >--at com.cardinfolink.yunshouyin.api.QuickPayApiImpl.getHistoryBills(QuickPayApiImpl.java:380)
 >--at com.cardinfolink.yunshouyin.core.QuickPayServiceImpl$7.doInBackground(QuickPayServiceImpl.java:189)
 >--at com.cardinfolink.yunshouyin.core.QuickPayServiceImpl$7.doInBackground(QuickPayServiceImpl.java:185)
 >--at android.os.AsyncTask$2.call(AsyncTask.java:287)
 >--at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
 >--... 5 more
channel '4209b698 com.cardinfolink.yunshouyin/com.cardinfolink.yunshouyin.activity.LoginActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
channel '4209b698 com.cardinfolink.yunshouyin/com.cardinfolink.yunshouyin.activity.LoginActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
Attempted to unregister already unregistered input channel '4209b698 com.cardinfolink.yunshouyin/com.cardinfolink.yunshouyin.activity.LoginActivity (server)'
: WIN DEATH: Window{4209b698 com.cardinfolink.yunshouyin/com.cardinfolink.yunshouyin.activity.LoginActivity paused=false}
: Process com.cardinfolink.yunshouyin (pid 7100) has died.

Change-Id: Id322b56d62fc0b31a6c8c9702dd9365ea7ebc175
Signed-off-by: Minghui Ma <mamh.ma@cardinfolink.com>